// <auto-generated />
namespace My.Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _5251006 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_5251006));
        
        string IMigrationMetadata.Id
        {
            get { return "201805250206419_5-25-10-06"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
