// <auto-generated />
namespace My.Project.MigrationsAddOne
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _4241340 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4241340));
        
        string IMigrationMetadata.Id
        {
            get { return "201804240540518_4-24-13-40"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
